
// generated by Davinci

'use strict';
import {createElement, Component, render} from 'rax';
import {View, Link, Text} from '@ali/rax-components';
import Picture from '@ali/rax-picture';


let styles = {
  fourthviewGroup: {
    width: 750,
    height: 1334
  },
  thirdviewGroup: {
    width: 750,
    height: 100
  },
  secondviewGroup: {
    width: 750,
    height: 100,
    backgroundColor: 'rgba(255,255,255,1)',
    boxShadow: '0 -2 5px 0 rgba(0,0,0,0.08)',
    flexDirection: 'column',
    paddingTop: 2
  },
  pictureGroup: {
    padding: 0,
    flexDirection: 'row'
  },
  picture: {
    width: 42,
    height: 43,
    marginLeft: 54,
    marginTop: 16
  },
  secondpicture: {
    width: 44,
    height: 39,
    marginLeft: 107,
    marginTop: 18
  },
  viewGroup: {
    padding: 0,
    marginLeft: 107,
    marginTop: 0,
    position: 'relative',
    flexDirection: 'column',
    paddingTop: 17
  },
  viewPicture: {
    width: 42,
    height: 42
  },
  textGroup: {
    width: 34,
    height: 34,
    left: 24,
    top: 0,
    backgroundColor: 'rgba(255,96,0,1)',
    borderWidth: 2,
    borderStyle: 'solid',
    borderColor: 'rgba(255,255,255,1)',
    borderRadius: 16,
    position: 'absolute',
    flexDirection: 'column',
    paddingTop: 2
  },
  text: {
    fontSize: 20,
    color: '#FFFFFF',
    letterSpacing: 0,
    lineHeight: '28rem',
    lines: 1,
    fontWeight: 400,
    marginLeft: 10,
    flexDirection: 'row'
  },
  secondviewPicture: {
    width: 40,
    height: 42,
    marginLeft: 93,
    marginTop: 17
  },
  thirdpicture: {
    width: 53,
    height: 53,
    marginLeft: 103,
    marginTop: 11
  },
  secondtextGroup: {
    padding: 0,
    marginTop: 1,
    flexDirection: 'row'
  },
  onFrontPage: {
    fontSize: 20,
    color: '#999999',
    letterSpacing: 0,
    lineHeight: '28rem',
    lines: 1,
    fontWeight: 400,
    marginLeft: 55
  },
  content: {
    fontSize: 20,
    color: '#999999',
    letterSpacing: 0,
    lineHeight: '28rem',
    lines: 1,
    fontWeight: 400,
    marginLeft: 110
  },
  news: {
    fontSize: 20,
    color: '#FF6000',
    letterSpacing: 0,
    lineHeight: '28rem',
    lines: 1,
    fontWeight: 400,
    marginLeft: 110
  },
  purchaseOfSingle: {
    fontSize: 20,
    color: '#999999',
    letterSpacing: 0,
    lineHeight: '28rem',
    lines: 1,
    fontWeight: 400,
    marginLeft: 100
  },
  info: {
    fontSize: 20,
    color: '#999999',
    letterSpacing: 0,
    lineHeight: '28rem',
    lines: 1,
    fontWeight: 400,
    marginLeft: 100
  }
};
let mockData = [{}];

class Mod extends Component {
  render() {
    let dataSource = this.props.data[0];
    return (
      <View style={styles.thirdviewGroup}>
        <View style={styles.secondviewGroup}>
          <View style={styles.pictureGroup}>
            <Picture source={{uri: 'https://gw.alicdn.com/tfs/TB1P6uzolfH8KJjy1XbXXbLdXXa-84-86.png'}} style={styles.picture} />
            <Picture source={{uri: 'https://gw.alicdn.com/tfs/TB1DokcofDH8KJjy1XcXXcpdXXa-88-78.png'}} style={styles.secondpicture} />
            <View style={styles.viewGroup}>
              <Picture source={{uri: 'https://gw.alicdn.com/tfs/TB176uzolfH8KJjy1XbXXbLdXXa-84-84.png'}} style={styles.viewPicture} />
              <View style={styles.textGroup}>
                <Text style={styles.text}>2</Text>
              </View>
            </View>
            <Picture source={{uri: 'https://gw.alicdn.com/tfs/TB1bzyzolfH8KJjy1XbXXbLdXXa-80-84.png'}} style={styles.secondviewPicture} />
            <Picture source={{uri: 'https://gw.alicdn.com/tfs/TB1pjyzolfH8KJjy1XbXXbLdXXa-106-106.png'}} style={styles.thirdpicture} />
          </View>
          <View style={styles.secondtextGroup}>
            <Text style={styles.onFrontPage}>首页</Text>
            <Text style={styles.content}>挑货</Text>
            <Text style={styles.news}>消息</Text>
            <Text style={styles.purchaseOfSingle}>进货单</Text>
            <Text style={styles.info}>我的</Text>
          </View>
        </View>
      </View>
    );
  }
}

render(<Mod data={mockData} />);
